# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.survey_statistics_question_statistics import SurveyStatisticsQuestionStatistics  # noqa: F401,E501
from swagger_server import util


class SurveyStatistics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total_responses: int=None, question_statistics: List[SurveyStatisticsQuestionStatistics]=None):  # noqa: E501
        """SurveyStatistics - a model defined in Swagger

        :param total_responses: The total_responses of this SurveyStatistics.  # noqa: E501
        :type total_responses: int
        :param question_statistics: The question_statistics of this SurveyStatistics.  # noqa: E501
        :type question_statistics: List[SurveyStatisticsQuestionStatistics]
        """
        self.swagger_types = {
            'total_responses': int,
            'question_statistics': List[SurveyStatisticsQuestionStatistics]
        }

        self.attribute_map = {
            'total_responses': 'total_responses',
            'question_statistics': 'question_statistics'
        }
        self._total_responses = total_responses
        self._question_statistics = question_statistics

    @classmethod
    def from_dict(cls, dikt) -> 'SurveyStatistics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SurveyStatistics of this SurveyStatistics.  # noqa: E501
        :rtype: SurveyStatistics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_responses(self) -> int:
        """Gets the total_responses of this SurveyStatistics.


        :return: The total_responses of this SurveyStatistics.
        :rtype: int
        """
        return self._total_responses

    @total_responses.setter
    def total_responses(self, total_responses: int):
        """Sets the total_responses of this SurveyStatistics.


        :param total_responses: The total_responses of this SurveyStatistics.
        :type total_responses: int
        """

        self._total_responses = total_responses

    @property
    def question_statistics(self) -> List[SurveyStatisticsQuestionStatistics]:
        """Gets the question_statistics of this SurveyStatistics.


        :return: The question_statistics of this SurveyStatistics.
        :rtype: List[SurveyStatisticsQuestionStatistics]
        """
        return self._question_statistics

    @question_statistics.setter
    def question_statistics(self, question_statistics: List[SurveyStatisticsQuestionStatistics]):
        """Sets the question_statistics of this SurveyStatistics.


        :param question_statistics: The question_statistics of this SurveyStatistics.
        :type question_statistics: List[SurveyStatisticsQuestionStatistics]
        """

        self._question_statistics = question_statistics
