# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SurveyStatisticsQuestionStatistics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, question_id: int=None, average_response: float=None, most_common_answer: str=None):  # noqa: E501
        """SurveyStatisticsQuestionStatistics - a model defined in Swagger

        :param question_id: The question_id of this SurveyStatisticsQuestionStatistics.  # noqa: E501
        :type question_id: int
        :param average_response: The average_response of this SurveyStatisticsQuestionStatistics.  # noqa: E501
        :type average_response: float
        :param most_common_answer: The most_common_answer of this SurveyStatisticsQuestionStatistics.  # noqa: E501
        :type most_common_answer: str
        """
        self.swagger_types = {
            'question_id': int,
            'average_response': float,
            'most_common_answer': str
        }

        self.attribute_map = {
            'question_id': 'question_id',
            'average_response': 'average_response',
            'most_common_answer': 'most_common_answer'
        }
        self._question_id = question_id
        self._average_response = average_response
        self._most_common_answer = most_common_answer

    @classmethod
    def from_dict(cls, dikt) -> 'SurveyStatisticsQuestionStatistics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SurveyStatistics_question_statistics of this SurveyStatisticsQuestionStatistics.  # noqa: E501
        :rtype: SurveyStatisticsQuestionStatistics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def question_id(self) -> int:
        """Gets the question_id of this SurveyStatisticsQuestionStatistics.


        :return: The question_id of this SurveyStatisticsQuestionStatistics.
        :rtype: int
        """
        return self._question_id

    @question_id.setter
    def question_id(self, question_id: int):
        """Sets the question_id of this SurveyStatisticsQuestionStatistics.


        :param question_id: The question_id of this SurveyStatisticsQuestionStatistics.
        :type question_id: int
        """

        self._question_id = question_id

    @property
    def average_response(self) -> float:
        """Gets the average_response of this SurveyStatisticsQuestionStatistics.


        :return: The average_response of this SurveyStatisticsQuestionStatistics.
        :rtype: float
        """
        return self._average_response

    @average_response.setter
    def average_response(self, average_response: float):
        """Sets the average_response of this SurveyStatisticsQuestionStatistics.


        :param average_response: The average_response of this SurveyStatisticsQuestionStatistics.
        :type average_response: float
        """

        self._average_response = average_response

    @property
    def most_common_answer(self) -> str:
        """Gets the most_common_answer of this SurveyStatisticsQuestionStatistics.


        :return: The most_common_answer of this SurveyStatisticsQuestionStatistics.
        :rtype: str
        """
        return self._most_common_answer

    @most_common_answer.setter
    def most_common_answer(self, most_common_answer: str):
        """Sets the most_common_answer of this SurveyStatisticsQuestionStatistics.


        :param most_common_answer: The most_common_answer of this SurveyStatisticsQuestionStatistics.
        :type most_common_answer: str
        """

        self._most_common_answer = most_common_answer
